config/routes.rb
Rails.application.routes.draw do
  resources :posts		
  devise_for :users, path: ""
  root "posts#index"
  get 'users/myposts'

  #match '/about', 	to: 'pages#about', via: :get
  get 'pages/about'




  resources :users, only: [:show]



end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :post

end

app/models/comment.rb
class Comment < ActiveRecord::Base

	belong_to :post

end

app/models/post.rb
class Post < ActiveRecord::Base

	belongs_to :user
	has_many :comments
	belongs_to :category
	validates_presence_of :title
	validates_presence_of :description



	has_attached_file :image, styles: { large: "600x600>", medium: "200x100+0+0", thumb: "150x150#" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :posts

  validates_presence_of :username, case_insensitive: false

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions.to_hash).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      elsif conditions.has_key?(:username) || conditions.has_key?(:email)
        where(conditions.to_hash).first
      end
  end


  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:avatar, :name, :username, :about, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/categories_category.rb
class CategoriesController < ApplicationController


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def about
		
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :find_post, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@posts = Post.all
	end

	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)

		if @post.save
			redirect_to @post
		else 
			render 'new'
		end
	end

	def show
		@post = Post.find(params[:id]) 
	end

	def update
		if @post.update(post_params)
			redirect_to @post
		else 
			render 'edit'
		end		
	end

	def edit
		
	end

	def destroy
		@post.destroy
		redirect_to root_path
	end


	private 
		def find_post
			@post = Post.find(params[:id])
		end

		def post_params
			params.require(:post).permit(:image, :title, :description, :avatar)
		end

		
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  	before_action :find_post, only: [:show, :avatar, :username, :name, :edit, :update, :destroy]


	def show
		 @user = User.find(params[:id])
		 @posts_post = @user.posts
	end

	def myposts
	 	@posts = Post.where(:user_id => current_user.id)
	end

	def create
	  @user = User.create( user_params )
	end

	def avatar
	    @user = current_user
	end




	 private 

		def find_post
			@post = User.find(params[:id])
		end

		def post_params
			params.require(:post).permit(:title, :description)
		end

		def user_params
		  params.require(:user).permit(:avatar)
		end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<p>Copyright WikiGeo</p>
</div>

app/views/layouts/_jumbotron.html.erb
<style> 

  .header-cover {
    background: url("/bg4.jpg");
    background-repeat: no-repeat;
    background-position: center;
     
  }

  .overlay {
  	background-color: Black;
    opacity: 0.4;
    width: 100%;
    height: 600px;
    position: absolute;
  }

</style>

<div class="overlay"></div>
<div class="header-cover">
	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-8" style="margin-top: 50px;">
			<h1 align="center">Moving with Geology. </h1>
		    <p align="center" class="heading-cover">WikiGeo BETA is a community of readers and writers offering unique perspectives on ideas large and small.</p><br>
			<p align="center">Sign up to read and interact with what matters most to you.</p>
		     <div align="center">
		     		<%= link_to("Login", new_user_session_path, 
		   	  		class: "btn btn-lg jumbobtn") %>
		   	  		<%= link_to("Sign Up", new_user_registration_path, 
		   	  		class: "btn btn-lg jumbobtn") %>
		     </div>
	     </div>
	     <div class="col-md-2"></div>
	</div>	    
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    
        <%= value %>
      
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "WikiGeo BETA 1.0", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to("Top Posts", new_post_path) %></li>
        <li><%= link_to("Top Users", new_post_path) %></li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to("Home", root_path) %></li>
        <li><%= link_to("About", pages_about_path) %></li>
        
        <% if user_signed_in? %>
          <li><%= link_to("Create", new_post_path) %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user"> <%= current_user.username %> </i><span class="caret"></span></a>
            <ul class="dropdown-menu"> 
              <li><%= link_to("My Posts", users_myposts_path) %></li>   
              <li><%= link_to("My Profile", edit_user_registration_path) %></li>
              <li><%= link_to("Logout", destroy_user_session_path, method: :delete) %></li>
            </ul>
          </li> 
        <% else %>
          <li><%= link_to("Log in", new_user_session_path) %></li>
          <li><%= link_to("Sign Up", new_user_registration_path) %></li>

        <% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wikigeo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= render "layouts/navbar" %>
<%= render 'layouts/messages' %>
<div class="">
 
	<%= yield %>


</div>



</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

app/views/posts/_form.html.erb
<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4 signupbg">


	<%= form_for @post, html: { multipart: true }  do |f| %>

		<div class="form-group">
			<%= f.file_field :image %>
		</div>	

		<div class="form-group">
			<%= f.label :title %>
			<%= f.text_field :title, class:"form-control" %>
		</div>

		<div class="form-group">
			<%= f.label :description %>
			<%= f.text_area :description, rows: 6, class:"form-control" %>
		</div>
			
		<%= f.submit class: "btn" %>

	<% end %>


   </div>  
    <div class="col-md-4"></div>
</div>

app/views/posts/edit.html.erb
<h1>Edit Posts </h1>


<%= render("form") %>

app/views/posts/index.html.erb
<% if user_signed_in? %>
  
<% else %>
  <%= render("layouts/jumbotron") %>
<% end %>

<div class="container">
<div class="row">
	
	<% @posts.each do |post| %>

		<div class="col-md-7 posts-main">
			<p class="postedby-main"><%= link_to " #{post.user.name}", post.user, class: "lead" %></p>
			<div class="thumb"><%= link_to (image_tag post.image.url(:medium)), post %></div>
			<h4><%= link_to post.title, post, class: "lead-title" %></h4>
			<p class="lead-para"><%= h truncate(post.description, length: 110) %><br><%= link_to "Read more...", post, class: "lead-read" %> </p>

		</div>

	<% end %>
	
</div>
</div>

app/views/posts/new.html.erb
<h1>Create Post </h1>

<%= render "form" %>

app/views/posts/show.html.erb
<%= image_tag @post.image.url(:large) %>

<h1><%= @post.title %></h1>

<h4><%= @post.description %></h4>

	
<% if @post.user == current_user %>
	<%= link_to "Edit", edit_post_path(@post), class: "btn btn-primary" %>
	<%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
<% end %>

app/views/users/myposts.html.erb
<% if @posts.size > 0 %>
	<h4>Thanks for sharing your Knowledge. You are Awesome :)</h4>
<% else %>
	<div class="row col-lg-12">
		<div class="alert alert-info quirkymsg" role="alert"><strong>You don't have any posts yet.<br>Start sharing your knowledge because i know you are awesome :)</strong></div>
	</div>	
<% end %>



	<% @posts.each do |post| %>
		
		<div class="box">
            <div class="panel panel-default">
			
			<div class="panel-body">
			 <h4><%= link_to post.title, post %></h4><br>
					
				Posted by:
				<%= post.user.username %>
				<span class="glyphicon glyphicon-comment" aria-hidden="true"></span>
				
				<span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
				
				<span class="glyphicon glyphicon-time" aria-hidden="true"></span>
				

			
			  </div>
            </div>
        </div>	
		
	<% end %>
	

app/views/users/show.html.erb
<div class="row"> 
	<div class="col-md-3 profile-border" align="center">
	<h2><%= @user.name %></h2>
		<%= image_tag @user.avatar.url(:thumb), class: "img-circle" %><br><br>
		<p class="profile-aatr">Username: <br><%= @user.username %> </p>
		<p class="profile-aatr">Email: <br><%= @user.email %> </p>
		<p class="profile-aatr">About: <br><%= @user.about %> </p>
	</div>	
	<div class="col-md-1"></div>
	<div class="col-md-8">
		<% if @user.posts.size > 0 %>
			
				<% @posts_post.each do |post| %>
					<%= link_to (image_tag post.image.url(:medium)), post %>
				    <h4><%= link_to post.title, post %></h4>
					
				<% end %>

		<% else %>
			
			<div class="no-posts"><strong>The user don't have <br>any posts yet. :(</strong></div>
			
		<% end %>
	</div>
</div>